core/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.index, name='index'),
    url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z_\\-]{1,60})/$',
        views.activate, name='activate'),
    path('meus_baralhos/', views.MeusBaralhosListView.as_view(), name='meus_baralhos'),
    path('baralho_adicionar_colaborador/<int:pk>/', views.BaralhoAdicionarColaborador.as_view(),
         name='baralho_adicionar_colaborador'),
    path('baralhos_publicos/', views.BaralhosListView.as_view(), name='public_baralhos'),
    path('cartoes_publicos/<int:pk>', views.PublicCartoesListView.as_view(), name='public_cartoes'),
    path('cartoes/<int:pk>/', views.CartaoListView.as_view(), name='cartoes'),
    path('editar_cartao/<int:pk>/', views.CartaoUpdateView.as_view(), name='editar_cartao'),
    path('criar_baralho/', views.BaralhoCreateView.as_view(), name='criar_baralho'),
    path('excluir_baralho/<pk>/', views.BaralhoDeleteView.as_view(), name='excluir_baralho'),
    path('criar_cartao/<int:baralho_pk>/', views.CartaoCreateView.as_view(), name='criar_cartao'),
    path('excluir_cartao/<pk>/', views.CartaoDeleteView.as_view(), name='excluir_cartao'),
    path('treinar_baralho/<int:baralho_pk>/', views.treinar_baralho, name='treinar_baralho'),
    path('atualizar_resposta/<cartao_pk>/', views.atualizar_resposta, name='resposta'),
    path('atualizar_resposta/<cartao_pk>/<acao>/', views.atualizar_resposta, name='resposta'),
    path('historico_revisoes/<cartao_pk>/<usuario_pk>', views.historico_revisoes, name='historico_revisoes'),
    path('acompanhamento_vinculados/<baralho_pk>', views.acompanhamento_vinculados, name='acompanhamento_vinculados'),
    path('rankings/', views.rankings, name='rankings'),
    path('alterar_visibilidade/<baralho_pk>/', views.alterar_visibilidade, name='alterar_visibilidade'),
    path('duplicar_baralho/<baralho_pk>/', views.duplicar_baralho, name='duplicar_baralho'),
    path('referenciar_baralho/<baralho_pk>/', views.referenciar_baralho, name='referenciar_baralho'),
]

home/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from core import views as core_views

urlpatterns = [
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^$', core_views.main, name=''),
    url(r'^about/$', core_views.about),
    path('core/', include('core.urls', namespace='core')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', core_views.signup, name='register'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# serving media files only on debug mode
if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT
        }),
    ]

core/models.py
from datetime import datetime, timedelta

from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey


class Comum(models.Model):

    """
        Model abstrato que reúne fields comuns a mais de um Model.
        Será portanto utilizado como classe mãe de models que precisem dos fields aqui definidos.
    """
    titulo = models.CharField(verbose_name='Título', max_length=255, blank=True, null=True)
    criado_em = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    criador = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        app_label = 'core'
        ordering = ('-id',)
        abstract = True


class Categoria(MPTTModel):
    """
        O Model categoria tem por objetivo definir a lista de categorias disponíveis para seleção.
        Posteriormente é utilizado em class Baralho. E nas views como forma de filtro por categoria.
    """
    parent = TreeForeignKey('self', related_name='children', on_delete=models.CASCADE, blank=True, null=True)
    titulo = models.CharField(verbose_name='Titulo', max_length=500)

    class MPTTMeta:
        order_insertion_by = ['titulo']
        unique_together = (('titulo', 'parent',),)

    def __str__(self):
        return self.titulo


class Baralho(Comum):
    """
    o model Baralho -que herda de Comum- define as propriedades de controle para o conjunto de cartões que
    será criado posteriormente.
    Observações:
        - O field booleano 'colaborativo' define se o baralho é colaborativo. Isso implica se pode ou náo possuir
        colaboradores.
        - O field 'colaboradores' permite criar uma lista de usuários-terceiros que poderão executar CRUD no baralho.
        - o field 'seguidores' define a lista de usuários seguidores. Esta lista é preenchida ao referenciar baralho.
    """

    descricao = models.TextField(verbose_name='Descrição', blank=True, null=True)
    publico = models.BooleanField(verbose_name='Baralho é público?', default=False)
    colaborativo = models.BooleanField(verbose_name='Baralho é Colaborativo?', default=False)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    colaboradores = models.ManyToManyField(User, verbose_name='Usuários Colaboradores', related_name='colaborador_list')
    seguidores = models.ManyToManyField(User, verbose_name='Usuários Seguidores do Baralho', related_name='seguidor_list')

    class Meta:
        verbose_name = 'Baralho'
        verbose_name_plural = 'Baralhos'

    def __str__(self):
        return f'{self.titulo}'


class Cartao(Comum):
    """
        O cartão é o model no qual é propriamente preenchido o conteúdo a ser memorizado.
    """
    baralho = models.ForeignKey(Baralho, on_delete=models.CASCADE)
    frente = RichTextUploadingField(verbose_name='Frente do Cartão', blank=True, null=True)
    verso = RichTextUploadingField(verbose_name='Verso do Cartão', blank=True, null=True)
    imagem_capa = models.ImageField(null=True, blank=True, max_length=300)

    class Meta:
        verbose_name = 'Cartão'
        verbose_name_plural = 'Cartões'

    def __str__(self):
        return f'{self.pk} - {self.titulo}'


class UsuarioCartao(models.Model):
    """
    O Model UsuarioCartao surge como uma tabela associativa de Usuário e Cartao. Tem por objetivo relacionar
    os diversos usuários aos diversos cartões.
    O campo historico_interacoes terá por objetivo armazenar um JSON contendo a data da revisão, a dificuldade
    atribuída, e se o usuário ainda lembrava da resposta do cartão na ocasião.
            Obs:
                O campo historico_interacoes é um JSON incremental, ou seja, inicialmente vazio,
                recebe uma lista do resultado da interação atual. Após o primeiro preenchimento,
                recebe o valor já armazenado acrescido da lista de valores da interação atual.
    """

    FACIL = 1
    FACIL_MEDIO = 2
    MEDIO = 3
    MEDIO_DIFICIL = 4
    DIFICIL = 5

    DIFICULDADE_CHOICES = [
        [FACIL, 'Fácil'],
        [FACIL_MEDIO, 'Fácil-Médio'],
        [MEDIO, 'Médio'],
        [MEDIO_DIFICIL, 'Médio-Difícil'],
        [DIFICIL, 'Difícil'],
    ]

    usuario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    cartao = models.ForeignKey(Cartao, on_delete=models.CASCADE)
    nivel_atual = models.PositiveSmallIntegerField(default=1)
    dificuldade_atual = models.CharField(
        verbose_name='Dificuldade Percebida',
        choices=DIFICULDADE_CHOICES,
        default='1',
        blank=True,
        max_length=10,
    )
    ultima_revisao = models.DateTimeField(verbose_name='Última Revisão em', blank=True, null=True)
    proxima_revisao = models.DateTimeField(verbose_name='Próxima Revisão em', blank=True, null=True)
    quantidade_revisoes = models.PositiveIntegerField(verbose_name='Quantidade de Revisões do Cartão', default=0,
                                                      blank=True)
    acertos = models.PositiveIntegerField(verbose_name='Quantidade de Confirmações de Memorização', default=0,
                                          blank=True)
    erros = models.PositiveIntegerField(verbose_name='Quantidade de Confirmações de Esquecimento', default=0,
                                        blank=True)
    historico_interacoes = models.JSONField(null=True, blank=True)
    streak = models.PositiveIntegerField(verbose_name='Maior sequência de acertos', default=0, blank=True)

    def get_proxima_revisao(self):
        return datetime.today() + timedelta(days=2 ** (self.nivel_atual - 1)) \
            if self.nivel_atual < 6 else datetime.today() + timedelta(days=30)

core/forms.py
from crispy_forms.helper import FormHelper
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from mptt.forms import TreeNodeChoiceField

from .models import Cartao, Baralho, Categoria


class RegistroUsuarioForm(UserCreationForm):
    email = forms.EmailField(max_length=254)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name')


class CartaoCreateForm(forms.ModelForm):
    class Meta:
        model = Cartao
        fields = ('titulo', 'frente', 'verso', )

        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control'}),
        }


class BaralhoCreateForm(forms.ModelForm):

    categoria = TreeNodeChoiceField(queryset=Categoria.objects.all())

    class Meta:
        model = Baralho
        fields = ('titulo', 'descricao', 'categoria', )

        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control'}),
            'descricao': forms.Textarea(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super(BaralhoCreateForm, self).__init__(*args, **kwargs)
        self.fields['categoria'].widget.attrs['class'] = 'form-control'


class BaralhoColaboradorForm(forms.ModelForm):

    colaboradores = forms.ModelMultipleChoiceField(
        label='Selecione os usuários que poderão editar e criar cartões',
        queryset=User.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = Baralho
        fields = ('colaboradores', )

    def __init__(self, *args, **kwargs):
        seguidores = kwargs.pop('seguidores', None)
        super(BaralhoColaboradorForm, self).__init__(*args, **kwargs)
        self.fields['colaboradores'].queryset = User.objects.filter(pk__in=[seguidores])

templates/core/acompanhamento_vinculados.html
{% extends 'core/base.html' %}

{% block content %}
{% if messages %}
    {% for message in messages %}
    <div class="container">
        <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
            {{ message }}
        </div>
        <a href="{% url 'core:meus_baralhos'%}" class="btn btn-primary">Voltar</a>
    </div>
    {% endfor %}
{% else %}
    <div class="container">
        <div style="text-align:center">
            <h4>Acompanhamento do baralho: {{ baralho }}.</h4>
            <div class="table-responsive">
                {% for cartao in page_obj %}
                    <table class="table table-striped table table-bordered">
                        <thead>
                        <tr>
                            <th colspan="7">Cartão {{ cartao.pk }} - {{ cartao.titulo }}</th>
                        </tr>
                        <tr>
                            <th>#</th>
                            <th>Usuário</th>
                            <th>Acertos</th>
                            <th>Erros</th>
                            <th>Qtd. Revisões</th>
                            <th>Última Revisão</th>
                            <th>Próxima Revisão</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for usuario_cartao in cartao.usuariocartao_set.all %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ usuario_cartao.usuario|title }}</td>
                            <td>{{ usuario_cartao.acertos}}</td>
                            <td>{{ usuario_cartao.erros }}</td>
                            <td>{{ usuario_cartao.quantidade_revisoes }}</td>
                            <td>{{ usuario_cartao.ultima_revisao|default_if_none:"Não Houve interação com o cartão" }}</td>
                            <td>{{ usuario_cartao.proxima_revisao }}</td>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% if not forloop.last %}
                    <hr>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
        {% if page_obj.paginator.num_pages > 1 %}
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center">
                    {% if page_obj.paginator.num_pages != 1 %}
                    <li class="page-item"><a class="page-link" href="?page=1">Primeira</a></li>
                    {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#">Primeira</a></li>
                    {% endif %}
                    {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#">&laquo;</a></li>
                    {% endif %}
                    {% for i in page_obj.paginator.page_range %}
                    {% if page_obj.number == i %}
                    <li class="page-item active"><a class="page-link" href="#">{{ i }}</a></li>
                    {% elif page_obj.number > i|add:"-5" and page_obj.number < i|add:"+5"%}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                    {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#">&raquo;</a></li>
                    {% endif %}
                    {% if page_obj.paginator.num_pages != page_obj.number %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Última</a></li>
                    {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#">Última</a></li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
        <a class="btn btn-primary" href="{% url 'core:meus_baralhos' %}">Voltar</a>
    </div>
    {% endif %}
{% endblock %}

templates/core/baralho_confirm_delete.html
{% extends 'core/base.html' %}
{% block content %}
    <div class="container">
        <form action="" method="post">{% csrf_token %}
            <p>Tem certeza que deseja deletar o {{ object }}?</p>
            <button class="btn btn-danger" type="submit">Excluir</button>
        </form>
    </div>
{% endblock %}

templates/core/baralho_form.html
{% extends 'core/base.html' %}
{% block content %}
<div class="container">
    <div class="form-group">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            {{ form.media }}
            <button class="btn btn-success"> Salvar </button>
        </form>
    </div>
</div>
{% endblock %}

templates/core/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <script src="https://kit.fontawesome.com/d14fb08352.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'core/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/misc.css' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>
  <body>
    <main>
      <div class="container">
        <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
          {% if user.is_authenticated %}
            <a href="/core" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
          {% else %}
            <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
          {% endif %}
            <img src="{% static 'img/logo.svg' %}" width="40" height="32" alt="logo">
            <svg class="bi me-2" width="1" height="1"><use xlink:href="#bootstrap"/></svg>
            <span class="fs-4">Memory Trigger</span>
          </a>
          <ul class="nav nav-pills">
            {% if user.is_authenticated %}
            <li class="nav-item"><a href="/core" class="nav-link" aria-current="page"><i class="fa-solid fa-home"></i> Início</a></li>
            <li class="nav-item"><a href="{% url 'core:meus_baralhos' %}" class="nav-link"><i class="fa-solid fa-inbox"></i> Meus Baralhos</a></li>
            <li class="nav-item"><a href="{% url 'core:public_baralhos' %}" class="nav-link"><i class="fa-brands fa-creative-commons-share"></i> Baralhos Públicos</a></li>
            <li class="nav-item"><a href="{% url 'core:rankings' %}" class="nav-link"><i class="fa-solid fa-ranking-star"></i> Ranking</a></li>
            <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link"><i class="fa-solid fa-arrow-right-from-bracket"></i> Sair</a></li>
            {% else %}
              <li class="nav-item"><a href="{% url 'login'%}" class="nav-link"><i class="fa-solid fa-user"></i> Login</a></li>
              <li class="nav-item"><a href="{% url 'register'%}" class="nav-link"><i class="fa-solid fa-user-plus"></i> Registrar</a></li>
              <li class="nav-item"><a href="/about/" class="nav-link"><i class="fa-solid fa-circle-info"></i> Sobre</a></li>
            {% endif %}
          </ul>
        </header>
      </div>
    </main>
  {% block content %}
  {% endblock %}
  </body>
  <footer class="footer mt-auto py-3 bg-light sticky-footer">
    <div class="container">
      <span class="text-muted">O Memory Trigger é um Software de código aberto de Repetição Espaçada com Flashcards.
        Contribua com a melhoria do projeto através do
        <a href="https://bit.ly/memory-trigger-repo">repositório oficial</a>.
        Saiba mais sobre a repetição espaçada e o artigo que gerou este sistema no
        <a href="https://bit.ly/memory-trigger-tcc">
          Trabalho de Conclusão de Curso</a>.</span>
    </div>
  </footer>
</html>

templates/core/cartoes.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
<style>
.card-img-top {
    width: 100%;
    height: 15vw;
    object-fit: cover;
}
</style>
<div class="container">
    <p>
        {% if object_list %}
        <a class="btn btn-success text-white" href="{% url 'core:treinar_baralho' baralho_pk %}" role="button" style="float: left;"> Treinar Memorização <i class="fa-regular fa-lightbulb"></i> </a>
        {% endif %}
        {% if pode_manipular %}
        <a class="btn btn-success" href="{% url 'core:criar_cartao' baralho_pk %}" role="button" style="float: right;">Adicionar Cartão <i class="fa-solid fa-circle-plus"></i></a>
        {% endif %}
    </p>
    <br><br>
</div>
<div class="container">
    <h1>Lista de Cartões do Baralho: {{ baralho.titulo }}</h1>
    {% if object_list %}
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for c in page_obj %}
                <div class="col">
                    <div class="card h-100">
                        <img src="{{ c.imagem_capa }}" class="card-img-top">
                        <div class="card-body">
                            <div class="dropdown" style="float: right;">
                                <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">Ações</button>
                                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
                                    <li><a class="dropdown-item" href="{% url 'core:historico_revisoes' c.pk request.user.pk %}">Histórico de Revisões</a></li>
                                    {% if pode_manipular %}
                                        <li><hr class="dropdown-divider"></li>
                                        <li><a class="dropdown-item" href="{% url 'core:editar_cartao' c.pk %}">Editar Cartão</a></li>
                                        {% if request.user == c.baralho.criador %}
                                            <li><a class="dropdown-item" href="{% url 'core:excluir_cartao' c.pk %}">Excluir Cartão</a></li>
                                        {% endif %}
                                    {% endif %}
                                </ul>
                            </div>
                            <h3>{{ c.titulo }}</h3>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">Criado em {{ c.criado_em }}</small>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        {% if is_paginated %}
            {% include 'core/pagination.html'%}
        {% endif %}
    {% else %}
        <p class="alert alert-warning">
            Você não possui nenhum cartão.
        </p>
    {% endif %}
</div>
{% endblock %}

templates/core/historico_revisoes.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="container table-responsive">
    {% if cartao.historico_interacoes %}
            <h4> Histórico de Revisões do Cartão {{ cartao.cartao.pk }}</h4>
            <hr>
            <ul>
                <li> Última Revisão deste cartão foi em: <strong>{{ cartao.ultima_revisao }}</strong></li>
                <li> A próxima revisão, preferencialmente, deve ser realizada em: <strong>{{ cartao.proxima_revisao }}.</strong></li>
            </ul>
            <table class="table table-striped table table-bordered">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Ação</th>
                    <th>Resultado</th>
                    <th>Acertos até a data</th>
                    <th>Erros até a data</th>
                    <th>Revisões até a data</th>
                    <th>Nível</th>
                    <th>Data</th>
                </tr>
                </thead>
                <tbody>
                {% for documento in cartao.historico_interacoes %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ documento.acao }}</td>
                        <td>{{ documento.resultado }}</td>
                        <td>{{ documento.acertos_data }}</td>
                        <td>{{ documento.erros_data }}</td>
                        <td>{{ documento.revisoes_data }}</td>
                        <td>{{ documento.nivel }}</td>
                        <td>{{ documento.data }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
    {% else %}
        <p class="alert alert-warning">Nenhuma revisão realizada para este cartão.</p>
    {% endif %}
    <a href="{% url 'core:index'%}" class="btn btn-primary">Voltar</a>
    </div>
{% endblock %}

templates/core/public_baralhos.html
{% extends 'core/base.html' %}

{% load widget_tweaks %}
{% load custom_filters %}

{% block content %}
<div class="container">
    <form method="get">
          <div class="row">
              <div class="form-group col-sm-4 col-md-3">
                  {{ filter.form.categoria.label_tag }}
                  {% render_field filter.form.categoria class="form-control" %}
              </div>
              <div class="form-group col-sm-4 col-md-3" >
                  <br>
                  <button type="submit" class="btn btn-success"> Filtrar <i class="fa-solid fa-magnifying-glass"></i></button>
              </div>
          </div>
    </form>
    <br>
    <h2>Baralhos Públicos</h2><hr>
    {% if object_list %}
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for bp in object_list %}
                <div class="col">
                    <div class="card h-100">
                        <div class="card-body">
                            <div class="dropdown" style="float: right;">
                                <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">Ações <i class="fa-solid fa-circle-plus"></i></button>
                                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
                                    <li><a class="dropdown-item" href="{% url 'core:public_cartoes' bp.pk %}" role="button">Ver Cartões</a></li>
                                    {% if bp.criador != request.user %}
                                        <li><a class="dropdown-item" href="{% url 'core:referenciar_baralho' bp.pk %}" role="button">Inscrever-se</a></li>
                                    {% endif %}
                                    {% if hoje > bp.criador.last_login|somar_dias:30 %}
                                        <li><a class="dropdown-item" href="{% url 'core:duplicar_baralho' bp.pk %}" role="button">Fazer cópia</a></li>
                                    {% endif %}
                                </ul>
                            </div>
                            <h4>{{ bp.titulo }}</h4>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">Categoria: {{ bp.categoria|title }}.</small><br>
                            <small class="text-muted">Criado por {{ bp.criador|title }}.</small><br>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p class="alert alert-warning">Não há baralhos públicos disponíveis.</p>
    {% endif %}
</div>
{% endblock %}

templates/core/public_cartoes.html
{% extends 'core/base.html' %}

{% block content %}
<div class="container">
    {% if object_list %}
        {% if page_obj.paginator.num_pages > 1 %}
            <a class="btn btn-primary" href="{% url 'core:public_baralhos' %}" role="button">Voltar</a>
        {% endif %}
        {% for c in page_obj %}
            <div class="p-5 mb-4 bg-light rounded-3">
                <h1> Cartão {{ c.titulo }}</h1>
                <h2> Frente do Cartão </h2>
                <p> {{ c.frente|safe }}</p>
                <h2> Verso </h2>
                <p> {{ c.verso|safe }}</p>
            </div>
        {% endfor %}
        {% if is_paginated %}
            {% include 'core/pagination.html'%}
        {% endif %}
    {% else %}
        <p class="alert alert-warning">Não há baralhos públicos disponíveis.</p>
    {% endif %}
    <a class="btn btn-primary" href="{% url 'core:public_baralhos' %}" role="button">Voltar</a>
</div>
{% endblock %}

templates/core/treinar_baralho.html
{% extends 'core/base.html' %}
{% block content %}
{% if cartoes %}
    {% for c in cartoes|dictsort:"pk" %}
        <div class="container">
            <div class="p-5 mb-4 bg-light rounded-3">
                <div class="card text-center">
                    <p>{{ c.cartao.frente|safe }}</p>
                    <div class="d-none" id="{{forloop.counter}}">
                        {{c.cartao.verso|safe}}<br>
                        <a class="btn btn-success" href="{% url 'core:resposta' c.cartao.pk 1 %}" role="button"> Lembro! </a>
                        <a class="btn btn-danger" href="{% url 'core:resposta' c.cartao.pk %}" role="button"> Não Lembro. </a>
                    </div>
                    <div>
                        <br>
                        <a class="btn btn-primary" onclick="verso({{forloop.counter}})" role="button" id="verso-{{forloop.counter}}"> Exibir Verso </a>
                    </div>&nbsp;
                </div>
            </div>
        </div>
    {% endfor %}
{% else %}
    <div class="container">
        <p class="alert alert-success">Você revisou todos os cartões disponíveis deste baralho para a data de hoje.</p>
        <a class="btn btn-primary" href="{% url 'core:index' %}">Voltar</a>
        <a class="btn btn-primary" href="{% url 'core:index' %}">Início</a>
    </div>
{% endif %}
<script>
    function verso(id){
        document.getElementById(id).classList.toggle('d-none');
        const btn = document.getElementById("verso-"+id);
        btn.innerText = btn.innerText === "Exibir Verso" ? 'Ocultar Verso' : 'Exibir Verso';
    }
</script>
{% endblock %}